### PR TITLE
Ensure default asset dirs also include trailing '/'

### LINKED ISSUE #46: Unset asset_path results in broken code
When not specifying asset_path, the default is used which generates code without trailing '/' which causes json loading to fail

### PR DESCRIPTION
**Pull request by NicolaVerbeeck**
Fixes #46

### CODE REVIEW

File: lib/src/locale_gen_params.dart [hunk 1]
```diff
@@ -10,8 +10,8 @@ final defaultLocaleAssetsDir = join('assets', 'locale');
 
 class LocaleGenParams {
   final String programName;
-  String? outputDir = defaultOutputDir;
-  String assetsDir = defaultAssetsDir;
+  String? outputDir = '$defaultOutputDir/';
+  String assetsDir = '$defaultAssetsDir/';
   String localeAssetsDir = defaultLocaleAssetsDir;
```
Comment (vanlooverenkoen) [inline lib/src/locale_gen_params.dart:15]: this dir variable will have the same problem.

**Review by vanlooverenkoen — CHANGES_REQUESTED** [review]

**Review by vanlooverenkoen — APPROVED** [review]
